apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-app-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: expense-app

  template:
    metadata:
      labels:
        app: expense-app

    spec:
      containers:
      - name: expense-app
        image: umair4004/expense-tracker:latest

        ports:
        - containerPort: 3000

        env:
        - name: MONGO_URL
          value: mongodb://mongo-service:27017/expenses
